### PR TITLE
fix: Implicit numeric conversion when generating id in normal mode

### LINKED ISSUE #20: Still getting deprecation notice for implicit conversion even after updating to v1.1.9
## Detailed description

After updating to 1.1.9, I am still getting this deprecation notice.

```shell
Implicit conversion from float 59.746165961027145 to int loses precision in /vendor/hidehalo/nanoid-php/src/Client.php on line 113
```

Code to reproduce
```php
use Hidehalo\Nanoid\Client as Nanoid;

$this->nanoid = new Nanoid();
$this->nanoid->generateId(10)
```
## Context

Using this to generate a default uniqueID for editorjs blocks from php

## Possible implementation

Explicit `int` casting

## Your environment

* PHP 8.1.1
* hidehalo/nanoid-php 1.1.9

### PR DESCRIPTION
**Pull request by betaSavvy**
## Description

Explicit cast to int to remove deprecation notice.

## Motivation and context

Fixes hidehalo/nanoid-php#20

## How has this been tested?

Ran `composer test` and passed all test.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

Go over all the following points, and put an `x` in all the boxes that apply.

Please, please, please, don't send your pull request until all of the boxes are ticked. Once your pull request is created, it will trigger a build on our [continuous integration](http://www.phptherightway.com/#continuous-integration) server to make sure your [tests and code style pass](https://help.github.com/articles/about-required-status-checks/).

- [x] I have read the **[CONTRIBUTING](CONTRIBUTING.md)** document.
- [x] My pull request addresses exactly one patch/feature.
- [x] I have created a branch for this patch/feature.
- [x] Each individual commit in the pull request is meaningful.
- [ ] I have added tests to cover my changes.
- [x] If my change requires a change to the documentation, I have updated it accordingly.

The existing tests already covers the needed assertions.

### CODE REVIEW

File: src/Client.php [hunk 1]
```diff
@@ -109,7 +109,7 @@ private function normalRandom($size)
     {
         $id = '';
         while (1 <= $size--) {
-            $rand = mt_rand()/(mt_getrandmax() + 1);
+            $rand = intval(mt_rand()/(mt_getrandmax() + 1));
```
Comment (hidehalo) [inline src/Client.php:112]: LGTM

Comment (hidehalo) [reply src/Client.php:112]: CI was closed for now... It's ok, I will merge and release new version.

**Review by hidehalo — APPROVED** [review]

**Comment by hidehalo** [comment]
Still buggy, see #25
